name: 'icure_medical_device_dart_sdk'
description: 'icure high level sdk for medical devices'
version: '1.5.3'

homepage: 'https://icure.dev'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: '>=0.13.0 <0.14.0'
  intl: '^0.17.0'
  meta: '^1.7.0'
  uuid: ^3.0.5
  icure_dart_sdk: ^1.1.2
  pointycastle: ^3.5.1
  crypton: ^2.0.3
  tuple: ^2.0.0
  crypto: ^3.0.1
  collection: ^1.16.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.20.1
